/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Aranzman;
import domen.Racun;
import domen.StavkaRacuna;
import domen.TipAranzmana;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import tabele.TableModelStavkeRacuna;

/**
 *
 * @author Rastko
 */
public class FMNoviRacun extends javax.swing.JDialog {

    /**
     * Creates new form FMNoviRacun
     */
    public FMNoviRacun(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        postaviDatumIBrojRacuna();
        popuniComboe();
        postaviTabelu();
    }

    public FMNoviRacun(java.awt.Frame parent, boolean modal, String klijent) {
        super(parent, modal);
        initComponents();
        postaviDatumIBrojRacuna();
        postaviKlijenta(klijent);
        popuniComboe();
        postaviTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labela_br_racuna = new javax.swing.JLabel();
        labela_datum = new javax.swing.JLabel();
        labela_klijent = new javax.swing.JLabel();
        jtxt_jmbg = new javax.swing.JTextField();
        jcmb_tipAranzmana = new javax.swing.JComboBox<>();
        jcmb_aranzman = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_stavke_racuna = new javax.swing.JTable();
        jbt_dodaj_stavku = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbt_sacuvaj_racun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Novi račun");

        jLabel2.setText("Br. računa:");

        jLabel3.setText("Datum:");

        labela_br_racuna.setText("numero");

        labela_datum.setText("danasnji");

        labela_klijent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labela_klijent.setText("ime klijenta");

        jcmb_tipAranzmana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TipAranzmana" }));

        jcmb_aranzman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aranzman" }));

        jtbl_stavke_racuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_stavke_racuna);

        jbt_dodaj_stavku.setText("Dodaj stavku");
        jbt_dodaj_stavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_dodaj_stavkuActionPerformed(evt);
            }
        });

        jLabel4.setText("JMBG:");

        jbt_sacuvaj_racun.setText("Sačuvaj račun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labela_br_racuna))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(labela_datum, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbt_sacuvaj_racun))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labela_klijent, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 66, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_jmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcmb_aranzman, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcmb_tipAranzmana, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_dodaj_stavku, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(labela_datum))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labela_br_racuna)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jcmb_tipAranzmana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jcmb_aranzman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_jmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_dodaj_stavku)
                    .addComponent(labela_klijent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_sacuvaj_racun)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_dodaj_stavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_dodaj_stavkuActionPerformed
        
        Aranzman ar = (Aranzman) jcmb_aranzman.getSelectedItem();
        TipAranzmana ta = (TipAranzmana) jcmb_tipAranzmana.getSelectedItem();        
        String jmbg = jtxt_jmbg.getText();        
        Date datum = new Date();
        int brojRacuna = Integer.parseInt(labela_br_racuna.getText());
        int iznos = 1;
        //POPRAVI OVO SVE
        //StavkaRacuna sr = new StavkaRacuna(brojRacuna, racun, ar, termin, brojRacuna, ar.getCena(), iznos);
    }//GEN-LAST:event_jbt_dodaj_stavkuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FMNoviRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FMNoviRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FMNoviRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FMNoviRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FMNoviRacun dialog = new FMNoviRacun(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_dodaj_stavku;
    private javax.swing.JButton jbt_sacuvaj_racun;
    private javax.swing.JComboBox<String> jcmb_aranzman;
    private javax.swing.JComboBox<String> jcmb_tipAranzmana;
    private javax.swing.JTable jtbl_stavke_racuna;
    private javax.swing.JTextField jtxt_jmbg;
    private javax.swing.JLabel labela_br_racuna;
    private javax.swing.JLabel labela_datum;
    private javax.swing.JLabel labela_klijent;
    // End of variables declaration//GEN-END:variables

    private void postaviDatumIBrojRacuna() {

        DateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        Date danasnji = new Date();
        labela_datum.setText(sdf.format(danasnji) + ".");

        try {
            LinkedList<Racun> ra = kontrolor.Kontrolor.getInstance().vratiListuRacuna();
            labela_br_racuna.setText(Integer.toString(ra.size() + 1));
        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Ne mogu da vratim racune");
            ex.printStackTrace();
        }

    }

    private void postaviKlijenta(String klijent) {
        labela_klijent.setText(klijent);
    }

    private void popuniComboe() {

        try {
            List<Aranzman> aranzmani = kontrolor.Kontrolor.getInstance().vratiListuAranzmanaPravih();
            List<TipAranzmana> tipovi = kontrolor.Kontrolor.getInstance().vratiListuAranzmana();
            jcmb_aranzman.setModel(new DefaultComboBoxModel(aranzmani.toArray()));
            jcmb_tipAranzmana.setModel(new DefaultComboBoxModel(tipovi.toArray()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ne mogu da popunim comboe");
        }

    }

    private void postaviTabelu() {
     
        TableModelStavkeRacuna tsr = new TableModelStavkeRacuna();
        jtbl_stavke_racuna.setModel(tsr);
        
    }
}
