/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Klijent;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import kontrolor.Kontrolor;
import tabele.TableModelKlijenti;

/**
 *
 * @author Rastko
 */
public class FMPretragaKlijenata extends javax.swing.JDialog {

    /**
     * Creates new form PretragaKlijenata
     */
    public FMPretragaKlijenata(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        documentListenerPretraga();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtn_detalji = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtxt_pretrazi = new javax.swing.JTextField();
        jbtn_pretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_klijenti = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga klijenata");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pretraga klijenata");

        jbtn_detalji.setText("Detalji...");
        jbtn_detalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_detaljiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unesite tekst pretrage:"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jtxt_pretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_pretraziActionPerformed(evt);
            }
        });

        jbtn_pretrazi.setText("Pretraži");
        jbtn_pretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_pretraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxt_pretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jbtn_pretrazi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_pretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_pretrazi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtbl_klijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_klijenti);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtn_detalji)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_detalji)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_detaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_detaljiActionPerformed

        int red = jtbl_klijenti.getSelectedRow();
        
        TableModelKlijenti tbl = (TableModelKlijenti) jtbl_klijenti.getModel();
        Klijent klijent = tbl.vratiKlijenta(red);
        Kontrolor.getInstance().getMapa().put("klijentKojiMiTreba",klijent);
        
        FMUnosKlijenata unos = new FMUnosKlijenata(this, true);
        
        try{
        unos.postaviVrednostiPolja(red);
        } catch (Exception e){ 
            JOptionPane.showMessageDialog(this, "Niste selektovali klijenta.");
        }
        unos.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jbtn_detaljiActionPerformed

    private void jbtn_pretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_pretraziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_pretraziActionPerformed

    private void jtxt_pretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_pretraziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_pretraziActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FMPretragaKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FMPretragaKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FMPretragaKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FMPretragaKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FMPretragaKlijenata dialog = new FMPretragaKlijenata(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_detalji;
    private javax.swing.JButton jbtn_pretrazi;
    private javax.swing.JTable jtbl_klijenti;
    private javax.swing.JTextField jtxt_pretrazi;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {

        try {
            List<Klijent> klijenti = Kontrolor.getInstance().vratiListuKlijenata();
            TableModelKlijenti tbl = new TableModelKlijenti(klijenti);
            jtbl_klijenti.getTableHeader().setReorderingAllowed(false);
            jtbl_klijenti.setModel(tbl);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    private void documentListenerPretraga(){
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
               pretrazi();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
               pretrazi();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
              pretrazi();
            }

        };
        jtxt_pretrazi.getDocument().addDocumentListener(dl);
    }
            private void pretrazi() {
                
                String pretraga = jtxt_pretrazi.getText().toLowerCase().trim();
                
                List<Klijent> klijenti = new LinkedList<>();
                
        try {
            List<Klijent> klijentiSVI = Kontrolor.getInstance().vratiListuKlijenata();
            for (Klijent klijent : klijentiSVI) {
                if(klijent.getIme().toLowerCase().contains(pretraga) ||
                        klijent.getPrezime().toLowerCase().contains(pretraga) || klijent.getMejl().contains(pretraga) ||
                            klijent.getTelefon().contains(pretraga) || klijent.getJmbg().contains(pretraga)){
                    klijenti.add(klijent);
                }
            }
            TableModelKlijenti tbl = new TableModelKlijenti(klijenti);
            jtbl_klijenti.setModel(tbl);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska");
        }
                
            }
}
