/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Aranzman;
import domen.Klijent;
import domen.Racun;
import java.text.ParseException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import tabele.TableModelAranzmani;
import tabele.TableModelRacun;

/**
 *
 * @author Rastko
 */
public class FMRacun extends javax.swing.JDialog {

    /**
     * Creates new form FMRacun
     */
    public FMRacun(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        postaviModelTabele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_pretraga_klijenta = new javax.swing.JTextField();
        btn_dodaj_novog = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jbt_obrisi_sa_racuna = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_racun = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbt_dodaj_na_racun = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_proizvodi = new javax.swing.JTable();
        jbt_pronadji = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rad sa računima");

        jLabel1.setText("Klijent:");

        jtxt_pretraga_klijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_pretraga_klijentaActionPerformed(evt);
            }
        });

        btn_dodaj_novog.setText("Dodaj novog");
        btn_dodaj_novog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dodaj_novogActionPerformed(evt);
            }
        });

        jbt_obrisi_sa_racuna.setText("Obrisi sa računa");
        jbt_obrisi_sa_racuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_obrisi_sa_racunaActionPerformed(evt);
            }
        });

        tabela_racun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela_racun);

        jButton1.setText("Sačuvaj");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt_obrisi_sa_racuna))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_obrisi_sa_racuna)
                    .addComponent(jButton1))
                .addGap(60, 60, 60))
        );

        jTabbedPane1.addTab("Racun", jPanel3);

        jbt_dodaj_na_racun.setText("Dodaj na racun");
        jbt_dodaj_na_racun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_dodaj_na_racunActionPerformed(evt);
            }
        });

        tabela_proizvodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabela_proizvodi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_dodaj_na_racun)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_dodaj_na_racun)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proizvodi", jPanel1);

        jbt_pronadji.setText("Pronađi");
        jbt_pronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_pronadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_pretraga_klijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbt_pronadji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_dodaj_novog)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_pretraga_klijenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_pronadji)
                    .addComponent(btn_dodaj_novog))
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_pretraga_klijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_pretraga_klijentaActionPerformed

        DocumentListener dockListenerNadji = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
    }//GEN-LAST:event_jtxt_pretraga_klijentaActionPerformed

    private void jbt_pronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_pronadjiActionPerformed

        try {
            String ime = jtxt_pretraga_klijenta.getText();
            LinkedList<Klijent> klijenti = (LinkedList<Klijent>) kontrolor.Kontrolor.getInstance().vratiListuKlijenata();

            for (Klijent klijent : klijenti) {

                String imePrezime = klijent.getIme() + " " + klijent.getPrezime();

                if (imePrezime.toLowerCase().contains(ime.toLowerCase())) {
                    ubaciRacunKlijentaUTabelu(klijent.getJmbg());
                    jtxt_pretraga_klijenta.setText(klijent.getIme() + " " + klijent.getPrezime());
                }
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }


    }//GEN-LAST:event_jbt_pronadjiActionPerformed

    private void btn_dodaj_novogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dodaj_novogActionPerformed

        FMUnosKlijenata fmuk = new FMUnosKlijenata(this, true);
        fmuk.setVisible(true);

    }//GEN-LAST:event_btn_dodaj_novogActionPerformed

    private void jbt_obrisi_sa_racunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_obrisi_sa_racunaActionPerformed

        TableModelRacun tmr = (TableModelRacun) tabela_racun.getModel();
        TableModelAranzmani tma = (TableModelAranzmani) tabela_proizvodi.getModel();

        try {
            int e = tabela_racun.getSelectedRow();
            Racun r = tmr.getRacuni().get(e);
            
            tma.getAranzmani().add(r.getAranzman());
            tma.fireTableDataChanged();
            
            tmr.obrisiRed(e);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Morate selektovati red.");
        }
    }//GEN-LAST:event_jbt_obrisi_sa_racunaActionPerformed

    private void jbt_dodaj_na_racunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_dodaj_na_racunActionPerformed

        TableModelAranzmani tma = (TableModelAranzmani) tabela_proizvodi.getModel();
        TableModelRacun tmr = (TableModelRacun) tabela_racun.getModel();

        try {
            Aranzman ar = tma.getAranzmani().get(tabela_proizvodi.getSelectedRow());
            tma.obrisiRed(tabela_proizvodi.getSelectedRow());
            tmr.ubaciAranzman(ar);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Morate selektovati aranzman.");
        }
    }//GEN-LAST:event_jbt_dodaj_na_racunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMRacun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FMRacun dialog = new FMRacun(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dodaj_novog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbt_dodaj_na_racun;
    private javax.swing.JButton jbt_obrisi_sa_racuna;
    private javax.swing.JButton jbt_pronadji;
    private javax.swing.JTextField jtxt_pretraga_klijenta;
    private javax.swing.JTable tabela_proizvodi;
    private javax.swing.JTable tabela_racun;
    // End of variables declaration//GEN-END:variables

    private void postaviModelTabele() {

        LinkedList<Racun> racuni = new LinkedList<>();
        TableModelRacun tmr = new TableModelRacun(racuni);
        tabela_racun.setModel(tmr);

        try {
            List<Aranzman> aranzmani = kontrolor.Kontrolor.getInstance().vratiListuAranzmanaPravih();
            TableModelAranzmani tma = new TableModelAranzmani(aranzmani);
            tabela_proizvodi.setModel(tma);
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Ne mogu da ucitam aranzmane.");
        }
    }

    private void ubaciRacunKlijentaUTabelu(String jmbg) {

        try {
            LinkedList<Racun> sr = kontrolor.Kontrolor.getInstance().vratiListuRacuna();
            TableModelRacun tmr = new TableModelRacun(sr);
            tabela_racun.setModel(tmr);
        } catch (Exception ex) {
            Logger.getLogger(FMRacun.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
