/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Klijent;
import java.awt.Dialog;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import kontrolor.Kontrolor;

/**
 *
 * @author Rastko
 */
public class FMUnosKlijenata extends javax.swing.JDialog {

    public FMUnosKlijenata(Dialog owner, boolean modal) {
        super(owner, modal);
        initComponents();
        setLocationRelativeTo(null);
        validacija();

    }

    /**
     * Creates new form FMUnosKlijenataa
     */
    public FMUnosKlijenata(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        setLocationRelativeTo(null);
        validacija();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telefonKlijenta_txt = new javax.swing.JTextField();
        sacuvajKlijenta_btn = new javax.swing.JButton();
        lbl_naslov = new javax.swing.JLabel();
        ponisti_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ImePrezimeKlijenta_txt = new javax.swing.JTextField();
        jmbgKlijenta_txt = new javax.swing.JTextField();
        eMailKlijenta_txt = new javax.swing.JTextField();
        jerror_ime_prezime = new javax.swing.JLabel();
        jerror_mail = new javax.swing.JLabel();
        jerror_telefon = new javax.swing.JLabel();
        jerror_jmbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos klijenata");

        telefonKlijenta_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonKlijenta_txtActionPerformed(evt);
            }
        });

        sacuvajKlijenta_btn.setText("Sačuvaj");
        sacuvajKlijenta_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacuvajKlijenta_btnActionPerformed(evt);
            }
        });

        lbl_naslov.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_naslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_naslov.setText("Novi klijent");

        ponisti_btn.setText("Poništi");
        ponisti_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponisti_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("Ime i prezime klijenta*:");

        jLabel3.setText("e-mail:");

        jLabel4.setText("Telefon:");

        jLabel5.setText("JMBG*:");

        ImePrezimeKlijenta_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImePrezimeKlijenta_txtActionPerformed(evt);
            }
        });

        jerror_ime_prezime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jerror_ime_prezime.setForeground(new java.awt.Color(255, 0, 51));

        jerror_jmbg.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_naslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(35, 35, 35)
                            .addComponent(ImePrezimeKlijenta_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(114, 114, 114)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jmbgKlijenta_txt)
                                .addComponent(eMailKlijenta_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(telefonKlijenta_txt))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ponisti_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sacuvajKlijenta_btn)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jerror_mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jerror_ime_prezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jerror_telefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jerror_jmbg, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_naslov, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ImePrezimeKlijenta_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jerror_ime_prezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMailKlijenta_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jerror_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonKlijenta_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jerror_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmbgKlijenta_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jerror_jmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sacuvajKlijenta_btn)
                    .addComponent(ponisti_btn))
                .addGap(0, 51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonKlijenta_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonKlijenta_txtActionPerformed

        String telefon = telefonKlijenta_txt.getText();
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
               if (telefon != "^[0][0-9]{8,9}$" || telefon != "^[+][0-9]{11,12}$"){
               jerror_telefon.setVisible(true);
                   jerror_telefon.setText("Morate uneti validan broj.");}
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (telefon != "^[0][0-9]{8,9}$" || telefon != "^[+][0-9]{11,12}$"){
               jerror_telefon.setVisible(true);
                   jerror_telefon.setText("Morate uneti validan broj.");}
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                if (telefon != "^[0][0-9]{8,9}$" || telefon != "^[+][0-9]{11,12}$"){
               jerror_telefon.setVisible(true);
                   jerror_telefon.setText("Morate uneti validan broj.");}
            }
        };
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonKlijenta_txtActionPerformed

    private void sacuvajKlijenta_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacuvajKlijenta_btnActionPerformed
        // TODO add your handling code here:
        Klijent klijent = new Klijent();

        String imePrezimeKlijenta = ImePrezimeKlijenta_txt.getText();
        String[] nizImena = imePrezimeKlijenta.split(" ");

        klijent.setIme(nizImena[0]);
        klijent.setPrezime(nizImena[1]);
        klijent.setMejl(eMailKlijenta_txt.getText());
        klijent.setJmbg(jmbgKlijenta_txt.getText());
        klijent.setTelefon(telefonKlijenta_txt.getText());
        try {
             System.out.println("forme.FMUnosKlijenata.sacuvajKlijenta_btnActionPerformed()");   
            Kontrolor.getInstance().unesiKlijenta(klijent);
            JOptionPane.showMessageDialog(this, "Uspešno ste uneli klijenta");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Klijent nije uspešno unet.");
        }
    }//GEN-LAST:event_sacuvajKlijenta_btnActionPerformed

    private void ponisti_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponisti_btnActionPerformed
        // TODO add your handling code here:
        jmbgKlijenta_txt.setText("");
        telefonKlijenta_txt.setText("");
        ImePrezimeKlijenta_txt.setText("");
        eMailKlijenta_txt.setText("");
    }//GEN-LAST:event_ponisti_btnActionPerformed

    private void ImePrezimeKlijenta_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImePrezimeKlijenta_txtActionPerformed

        String ime = ImePrezimeKlijenta_txt.getText();
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if (!ime.contains(" ")) {
                    jerror_ime_prezime.setText("Morate uneti Ime pa Prezime");
                }
                jerror_ime_prezime.setVisible(true);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (!ime.contains(" ")) {
                    jerror_ime_prezime.setText("Morate uneti Ime pa Prezime");
                }
                jerror_ime_prezime.setVisible(true);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                if (!ime.contains(" ")) {
                    jerror_ime_prezime.setText("Morate uneti Ime pa Prezime");
                }
                jerror_ime_prezime.setVisible(true);
            }
        };

    }//GEN-LAST:event_ImePrezimeKlijenta_txtActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FMUnosKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FMUnosKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FMUnosKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FMUnosKlijenata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FMUnosKlijenata dialog = new FMUnosKlijenata(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ImePrezimeKlijenta_txt;
    private javax.swing.JTextField eMailKlijenta_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jerror_ime_prezime;
    private javax.swing.JLabel jerror_jmbg;
    private javax.swing.JLabel jerror_mail;
    private javax.swing.JLabel jerror_telefon;
    private javax.swing.JTextField jmbgKlijenta_txt;
    private javax.swing.JLabel lbl_naslov;
    private javax.swing.JButton ponisti_btn;
    private javax.swing.JButton sacuvajKlijenta_btn;
    private javax.swing.JTextField telefonKlijenta_txt;
    // End of variables declaration//GEN-END:variables

    void postaviVrednostiPolja(int red) {

        Klijent klijent = (Klijent) Kontrolor.getInstance().getMapa().get("klijentKojiMiTreba");

        lbl_naslov.setText("Detalji o klijentu");
        ImePrezimeKlijenta_txt.setText(klijent.getIme() + " " + klijent.getPrezime());
        telefonKlijenta_txt.setText(klijent.getTelefon());
        eMailKlijenta_txt.setText(klijent.getMejl());
        jmbgKlijenta_txt.setText(klijent.getJmbg());

        ImePrezimeKlijenta_txt.setEditable(false);
        telefonKlijenta_txt.setEditable(false);
        eMailKlijenta_txt.setEditable(false);
        jmbgKlijenta_txt.setEditable(false);
        ImePrezimeKlijenta_txt.setEnabled(false);

        ponisti_btn.setVisible(false);
        sacuvajKlijenta_btn.setVisible(false);

    }

    private void validacija() {

        ListenerImePrezime();
        listenerTelefon();
        
    }

    private void ListenerImePrezime() {
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                System.out.println(telefonKlijenta_txt.getText());
                proveriImePrezime();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                proveriImePrezime();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                proveriImePrezime();
            }

        };
        ImePrezimeKlijenta_txt.getDocument().addDocumentListener(dl);
    }

    private void proveriImePrezime() {
        String unos = ImePrezimeKlijenta_txt.getText().toLowerCase();

        if (!unos.contains(" ")) {
            jerror_ime_prezime.setText("Morate uneti jedno ime i jedno prezime");
            jerror_ime_prezime.setVisible(true);
            
            return;
        }

        if (unos == "") {
            jerror_ime_prezime.setText("Ovo polje je obavezno");
            return;
        }
        
        String[] niz = unos.split(" ");
        if (niz.length != 2) {
            jerror_ime_prezime.setText("Uneli ste vise od jednog prezimena");
            return;
        }
        jerror_ime_prezime.setText("");
        
    }

    private void listenerTelefon() {

        
        
        String telefon = telefonKlijenta_txt.getText();
        
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                proveriTelefon(telefon);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                proveriTelefon(telefon);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                proveriTelefon(telefon);
            }
        };
        telefonKlijenta_txt.getDocument().addDocumentListener(dl);
    }
    
    public void proveriTelefon(String telefon) {
        
        
        
        jerror_telefon.setVisible(true);
        
        if (!telefon.contains("[0-9]{8,9}$")){
                   jerror_telefon.setVisible(true);
                   jerror_telefon.setText("Morate uneti validan broj.");
                    return;
        }
        
        if (telefon == ""){
            jerror_telefon.setVisible(true);
            jerror_telefon.setText("Ovo polje je obavezno.");
                return;
        }
        
        jerror_telefon.setText("");
        
    }
    

}
